### ISSUE TITLE
Cannot install addon with npm

### ISSUE THREAD

**Issue by mikzar** [Suven/ember-cli-swiper#1]
Hi,

I couldn't install the addon directly through npm.

Here's the error message:
```
$ ember install ember-cli-swiper
version: 2.4.2
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
/Users/mikzar/development/ember-project/node_modules/ember-cli-swiper/blueprints/ember-cli-swiper/index.js:4
  normalizeEntityName() {
                     ^
Unexpected token (
/Users/mikzar/development/ember-project/node_modules/ember-cli-swiper/blueprints/ember-cli-swiper/index.js:4
  normalizeEntityName() {
                     ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (/Users/mikzar/development/ember-project/node_modules/ember-cli/lib/models/blueprint.js:1358:25)
    at Function.Blueprint.lookup (/Users/mikzar/development/ember-project/node_modules/ember-cli/lib/models/blueprint.js:1333:24)
    at Class.module.exports.Task.extend.lookupBlueprint (/Users/mikzar/development/ember-project/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:91:22)
```

It seems like I managed to use the addon anyway by installing the module locally (`$ npm install node_modules/ember-cli-swiper/`), but then I had another error when starting the server:
```
 ember s -pr http://localhost:3000
/Users/mikzar/development/ember-project/node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
Unexpected token (
/Users/mikzar/development/ember-project/node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (/Users/mikzar/development/ember-project/node_modules/ember-cli/lib/models/addon.js:859:19)
    at /Users/mikzar/development/ember-project/node_modules/ember-cli/lib/models/addons-factory.js:47:36
    at visit (/Users/mikzar/development/ember-project/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

In `node_modules/ember-cli-swiper/index.js`, I changed the line
```
included(app) {
  ...
}
```
by
```
included: function(app) {
  ...
}
```
and it finally worked.

Could take a look at this ?

Best

**Comment by Suven** [comment]
Hey,

since I developed using Ember 2 and am using DockYard/ember-suave to enforce a common cs, this plugin requires you to run a recent version of node (which understands more of the ES15-syntax).

Is updating node an option for you? Which version are you running?

**Comment by signal-intrusion** [comment]
+1

Sometimes updating node isn't an option, depending on your project/client's tech stack.

**Comment by mikzar** [comment]
I was using the latest Ember release (2.4.2), with an older version of node (0.12.4).
I upgraded node to the latest stable release (v5.10.1), and the installation of the `ember-cli-swiper` went well.

Thanks!

**Comment by Suven** [comment]
Great (:

@signal-intrusion That is right, but as we are speaking about the env that builds the ember-application I think it's safe to make stronger assumption/requirements about what it should run. I'm quite sure you will have those problems more and more often in the next few weeks; not only with this addon.
