### ISSUE TITLE
Fastboot Issue

### ISSUE THREAD

**Issue by ivanhueso** [Suven/ember-cli-swiper#62]
I've pull the latest release and I have issues with Fastboot. The following error appears.

    TypeError: Cannot read property 'userAgent' of undefined
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-8TjGpyul.tmp/assets/swiper.js:4497:29
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-8TjGpyul.tmp/assets/swiper.js:4498:102
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-8TjGpyul.tmp/assets/swiper.js:5337:21
       at ContextifyScript.Script.runInContext (vm.js:35:29)
       at VMSandbox.eval (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/vm-sandbox.js:14:16)
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:136:15
       at Array.forEach (native)
       at EmberApp.loadAppFiles (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:133:21)
       at EmberApp.retrieveSandboxedApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:181:10)
       at new EmberApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:49:21)
       at FastBoot._buildEmberApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/index.js:114:17)
       at new FastBoot (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/index.js:52:10)
       at app.use (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-fastboot/index.js:247:29)
       at Layer.handle [as handle_request] (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/layer.js:95:5)
       at trim_prefix (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:317:13)
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:284:7
       at Function.process_params (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:335:12)
       at next (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:275:10)
       at err (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
       at watcher.then (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
       at tryCatch (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
       at invokeCallback (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
       at flush (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
       at _combinedTickCallback (internal/process/next_tick.js:73:7)
       at process._tickCallback (internal/process/next_tick.js:104:9)`

What can I do?

**Comment by Suven** [comment]
Hey,

do you mean you pulled the latest release from npm or from git? We just merged support for fastboot, but didn't publish a new npm-version yet.

**Comment by ivanhueso** [comment]
Hi Sueven,

I've run `ember install ember-cli-swiper` command and it install `"ember-cli-swiper": "^0.6.0"` package. is this correct or what should I do?

**Comment by ivanhueso** [comment]
I have changed the version to ` "ember-cli-swiper": "c9a8c812ea72ca3565868a1d63275dfd341db484",` but when I run npm install I get:

> No compatible version found: ember-cli-swiper@c9a8c812ea72ca3565868a1d63275dfd341db484

**Comment by ivanhueso** [comment]
Ok, So I changed to the version `c9a8c812ea72ca3565868a1d63275dfd341db484` and run npm install again, but now I got the following error:
    
    BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
      TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
      at BroccoliMergeTrees.Plugin (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-plugin/index.js:23:13)
      at new BroccoliMergeTrees (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-swiper/node_modules/broccoli-merge-trees/index.js:42:10)
      at Class.treeForVendor (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-swiper/index.js:25:12)
      at Class._treeFor (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/models/addon.js:551:33)
      at Class.treeFor (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/models/addon.js:511:21)
      at project.addons.map.addon (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:557:22)
      at Array.map (native)
      at EmberApp.addonTreesFor (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:555:32)
      at EmberApp._processedVendorTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:979:24)
      at EmberApp._processedExternalTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:1007:25)

**Comment by renatocarvalho** [comment]
I was having the same issue. I changed `ember-cli-swiper` package version to the `master` branch of this repo and started to work again 🙌

`"ember-cli-swiper": "Suven/ember-cli-swiper"`

**Comment by cecemel** [comment]
@ivanhueso I have the same issue, did you manage to fix it? (I tried installing all the branches and forks I found related to this issue, but didn't work)

**Comment by jelhan** [comment]
@ivanhueso and @cecemel: This one should be fixed by #64

**Comment by Matt-Jensen** [comment]
I've carefully reviewed @jelhan's code (now merged master) and have successfully installed and run in Fastboot. Since this issue is long overdue I'd like to get this published to npm ASAP.  Issue is that that tests are now failing due to fun and ✨mystical reasons✨.

Likely we just need to migrate this addon to ember-cli to ^2.14.0 in order to fix the dependency soup that has gone bad.

**Comment by jelhan** [comment]
@Matt-Jensen: I've rerun all tests on master and all five scenarios are passing for me.

yarn v0.27.5
bower 1.8.0

```$ bower list
$ bower list
bower check-new     Checking for new versions of the project dependencies...
ember-cli-swiper /home/main/tmp/ember-cli-swiper
├─┬ ember#2.10.2 (latest is 2.15.0-beta.3)
│ └── jquery#3.2.1
├─┬ ember-cli-shims#0.1.3 (latest is 1.2.0-beta.2)
│ └── ember#2.10.2 (2.15.0-beta.3 available)
└─┬ ember-qunit-notifications#0.1.0
  └── qunit-notifications#0.1.1 (latest is 1.0.0)
```

**Comment by Matt-Jensen** [comment]
@jelhan confirming this is a dependency issue (I believe related to testem).  Installing with yarn fixes the issue and [Travis CI continues to successfully run tests](https://travis-ci.org/Suven/ember-cli-swiper) with node v8.4.0 and npm v5.3.0 as well.   However neither option provides us much of a guarantee moving forward.

I've made an issue to migrate this addon's ember-cli version and commit a `package-lock.json` file as well #67.

@Suven recommend you run `npm publish` on master (now v0.6.1)

**Comment by Suven** [comment]
@Matt-Jensen did so

Thanks for everyones contributions
