### ISSUE TITLE
build error on ember 2.16

### ISSUE THREAD

**Issue by 0xadada** [Suven/ember-cli-swiper#74]
When doing a `production` build, i get the following build error

```
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/Users/ron/cinch/advisor/tmp/uglify_writer-input_base_path-kCMItc3z.tmp/assets/maps/swiper.min.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at UglifyWriter.processFile (/Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (native)
    at /Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (native)
    at UglifyWriter.build (/Users/ron/cinch/advisor/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /Users/ron/cinch/advisor/node_modules/broccoli-plugin/read_compat.js:93:34

The broccoli plugin was instantiated at:
    at Fingerprint.Plugin (/Users/ron/cinch/advisor/node_modules/broccoli-plugin/index.js:7:31)
    at Fingerprint.Filter [as constructor] (/Users/ron/cinch/advisor/node_modules/broccoli-filter/index.js:34:10)
    at new Fingerprint (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:21:10)
    at Fingerprint (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/fingerprint.js:16:12)
    at new AssetRev (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:31:25)
    at AssetRev (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/lib/asset-rev.js:7:12)
    at Class.postprocessTree (/Users/ron/cinch/advisor/node_modules/broccoli-asset-rev/index.js:31:40)
    at projectOrAddon.addons.reduce (/Users/ron/cinch/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/ron/cinch/advisor/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
```

## ember version

```
ember-cli: 2.16.2
node: 6.11.2
os: darwin x64
```

## package.json
```javascript
"devDependencies": {
    "bower": "^1.8.0",
    "broccoli-asset-rev": "^2.6.0",
    "broccoli-clean-css": "^2.0.1",
    "broccoli-funnel": "^2.0.1",
    "broccoli-merge-trees": "^2.0.0",
    "cordova": "^7.0.1",
    "cordova-plugin-crosswalk-webview": "^2.3.0",
    "dotenv": "^4.0.0",
    "ember-ajax": "^3.0.0",
    "ember-auto-focus": "^2.0.1",
    "ember-changeset": "^1.3.0",
    "ember-changeset-validations": "^1.2.8",
    "ember-cli": "~2.16.2",
    "ember-cli-accounting": "^2.0.1",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.7.2",
    "ember-cli-content-security-policy": "^1.0.0",
    "ember-cli-dependency-checker": "^2.0.1",
    "ember-cli-deploy": "^1.0.1",
    "ember-cli-deploy-aws-pack": "^1.0.0",
    "ember-cli-deploy-build": "^1.1.0",
    "ember-cli-deploy-display-revisions": "^1.0.0",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-s3-index": "^1.0.0",
    "ember-cli-document-title": "^0.3.3",
    "ember-cli-eslint": "^4.2.0",
    "ember-cli-foundation-6-sass": "^0.0.24",
    "ember-cli-htmlbars": "^2.0.3",
    "ember-cli-htmlbars-inline-precompile": "^1.0.2",
    "ember-cli-inject-live-reload": "^1.7.0",
    "ember-cli-json-pretty": "^0.1.2",
    "ember-cli-moment-shim": "^3.4.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-sass": "^7.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-stylelint": "^1.0.0",
    "ember-cli-swiper": "^0.6.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-cli-update": "^0.9.1",
    "ember-cli-uuid": "^0.4.1",
    "ember-concurrency": "^0.8.7",
    "ember-cordova": "^1.0.3",
    "ember-cordova-platform": "^0.1.0",
    "ember-cordova-splash": "^0.1.4",
    "ember-cp-validations": "^3.4.0",
    "ember-data": "~2.16.2",
    "ember-elsewhere": "^1.0.2",
    "ember-export-application-global": "^2.0.0",
    "ember-font-awesome": "^3.0.5",
    "ember-freestyle": "^0.6.1",
    "ember-gestures": "^0.4.5",
    "ember-hammertime": "^1.2.3",
    "ember-hook": "^1.4.2",
    "ember-i18n": "^5.0.2",
    "ember-inputmask": "^0.4.0-beta.4",
    "ember-load-initializers": "^1.0.0",
    "ember-metrics": "^0.12.1",
    "ember-moment": "^7.4.1",
    "ember-new-relic": "^0.5.2",
    "ember-phoenix-shim": "^0.1.0",
    "ember-power-select": "^1.9.6",
    "ember-radio-button": "^1.1.1",
    "ember-resolver": "^4.3.0",
    "ember-route-action-helper": "^2.0.5",
    "ember-simple-auth": "^1.4.0",
    "ember-source": "~2.16.2",
    "ember-svg-jar": "^0.11.1",
    "ember-truth-helpers": "^1.3.0",
    "ember-user-activity": "^0.9.0",
    "liquid-fire": "^0.27.3",
    "loader.js": "^4.2.3",
    "phoenix": "^1.2.1",
    "stylelint-config-standard": "^17.0.0"
  },
```

**Comment by 0xadada** [comment]
Workaround for this was to disable sourcemaps in production builds

## ember-cli-build.js

```javascript
// ...
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

// ...
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: EmberApp.env() !== 'production',
    },
   // ...
```

**Comment by Matt-Jensen** [comment]
Successfully built in production on a fresh ember-cli 2.16.2 app.

```
ember-cli: 2.16.2
node: 6.11.5
os: darwin x64
```

Please confirm you can reproduce on a fresh ember-cli app and we can debug further.

**Comment by 0xadada** [comment]
I'm unable, looks like the npm package hasn't been published https://www.npmjs.com/package/ember-cli-swiper

**Comment by Matt-Jensen** [comment]
@Suven still needs to publish v0.7.0, but `^0.6.0` in you package is published.
